### ISSUE TITLE
i2c address can be 0x6a

### ISSUE THREAD

**Issue by gauteh** [sousandrei/ism330dhcx#2]
Hi, on my deb board the sensor is at i2c 0x6a: https://learn.adafruit.com/lsm6dsox-and-ism330dhc-6-dof-imu/arduino , maybe this can be configurable somehow?

**Comment by sousandrei** [comment]
Seems like a good idea! I'll work on it :D

**Comment by gauteh** [comment]
Thanks, found small bug, fixed in #5 .
