### ISSUE TITLE
Evaluation board?

### ISSUE THREAD

**Issue by gauteh** [sousandrei/ism330dhcx#7]
Hi,

do you have experience with different evaluation boards with the ISM330DHCX? The one I am using is out of stock.

Regards, Gaute

**Comment by sousandrei** [comment]
The one I use is the ST's [x-nucleo-iks02a1](https://www.st.com/en/ecosystems/x-nucleo-iks02a1.html)

**Comment by gauteh** [comment]
Thanks!
